name: Menjalankan bot absensi keluar otomatis

on:
  schedule:
    # Menjalankan cron job setiap pukul 13.00 pagi WIB
    # Dari hari Senin sampai Jum'at, Disini di set
    # 06:00 karena zona waktu yang dipakai github action
    # adalah zona waktu UTC, atur sesuai jam yang diinginkan
    # dan sesuai dengan zona waktumu
    - cron: "0 6 * * 1-5"
  workflow_dispatch:

jobs:
  absen:
    runs-on: ubuntu-latest
    name: Jalankan botnya!

    steps:
      - uses: actions/checkout@v2
      - name: Setup NodeJS 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Install Node Dependencies
        run: npm install

      - name: Waktunya absen keluar
        run: npm run logout
        env:
          SUCCESS_INDICATOR_ELEMENTS: ${{ secrets.SUCCESS_INDICATOR_ELEMENTS }}

          # Required Field
          WEBSITE_URL: ${{ secrets.WEBSITE_URL }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          LOGOUT_BOX: ${{ secrets.LOGOUT_BOX }}
          LOGOUT_BUTTON: ${{ secrets.LOGOUT_BUTTON }}
          CONFIRM_LOGOUT_BUTTON: ${{ secrets.CONFIRM_LOGOUT_BUTTON }}

          # Optional Field, uncomment if needed
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          FORM_WRAPPER: ${{ secrets.FORM_WRAPPER }}
          # INPUT_USERNAME: ${{ secrets.INPUT_USERNAME }}
          # INPUT_PASSWORD: ${{ secrets.INPUT_PASSWORD }}
          # BUTTON_SUBMIT: ${{ secrets.BUTTON_SUBMIT }}
